import type { ModuleDefinition, PortDefinition, ControlDefinition, SignalDomain, SettingValue } from './moduleDefinitions.ts';

// R3-S selected modes only. The seven prototype definitions are never replaced.
const p = (id: string, family: SignalDomain, direction: 'in' | 'out', scale = 1, clock = false): PortDefinition =>
    ({ id, label: id, binding: id, family, direction, scale, ...(direction === 'in' ? { maxConnections: 1, smoothing: 'none' as const } : {}), ...(clock ? { accepts: ['CLOCK'] } : {}) });
const c = (id: string, min: number, max: number, step: number, initial: number, unit: string, integer = false): ControlDefinition =>
    ({ id, label: id, binding: id, min, max, step, initial, unit, ...(integer ? { integer: true } : {}) });
const freeze = <T,>(value: T): T => { if (value && typeof value === 'object') { for (const item of Object.values(value)) freeze(item); Object.freeze(value); } return value; };
const selected = (definitionId: string, productId: string, name: string, behaviorId: string, ports: PortDefinition[], controls: ControlDefinition[], values: Record<string, SettingValue>): ModuleDefinition =>
    freeze({ definitionId, definitionVersion: 1, productId, name, subtitle: 'R3-S selected mode; full R1 product contract remains partial',
        behaviorId, behaviorVersion: 1, ports, controls, initialControlsImmediate: true,
        settings: Object.fromEntries(Object.entries(values).map(([key, initial]) => [key, { initial, options:
            key === 'run' || key.startsWith('cycle') ? [false, true] : key.startsWith('curve') ? ['linear', 'exponential'] : [initial] }])) });

export const STARTER_DEFINITIONS: Readonly<Record<string, ModuleDefinition>> = {
    'catalogue.solar-sine.selected': selected('catalogue.solar-sine.selected', 'catalogue.solar-sine', "Solar Sine", 'osc.periodic-selected',
        [p("pitch", 'CV', 'in', 1200), p("out", 'AUDIO', 'out', 1)],
        [c('frequency', 40, 1200, 1, 110, "Hz")],
        {"waveform":"sine"}),
    'catalogue.gramps-saw.selected': selected('catalogue.gramps-saw.selected', 'catalogue.gramps-saw', "Gramps’ Saw", 'osc.periodic-selected',
        [p("pitch", 'CV', 'in', 1200), p("out", 'AUDIO', 'out', 1)],
        [c('frequency', 40, 1200, 1, 111, "Hz")],
        {"waveform":"sawtooth","driftEnabled":false}),
    'catalogue.fusion-filter.selected': selected('catalogue.fusion-filter.selected', 'catalogue.fusion-filter', "Fusion Ladder Filter", 's1a.filter',
        [p("in", 'AUDIO', 'in', 1), p("cutoff", 'CV', 'in', 2400), p("out", 'AUDIO', 'out', 1)],
        [c('cutoff', 40, 12000, 1, 600, "Hz"), c('resonance', 0.1, 20, 0.1, 1.6, "Q")],
        {"cutoffCvCentsPerUnit":2400}),
    'catalogue.ghost-vca.selected': selected('catalogue.ghost-vca.selected', 'catalogue.ghost-vca', "Ghost Gate VCA", 's1a.vca',
        [p("in", 'AUDIO', 'in', 1), p("gain", 'CV', 'in', 0.5), p("out", 'AUDIO', 'out', 1)],
        [c('level', 0, 1, 0.01, 0.4, "nonnegative gain bias")],
        {"gainCvPerUnit":0.5}),
    'catalogue.void-delay.selected': selected('catalogue.void-delay.selected', 'catalogue.void-delay', "Void Delay", 's1a.delay',
        [p("in", 'AUDIO', 'in', 1), p("return", 'AUDIO', 'in', 1), p("out", 'AUDIO', 'out', 1)],
        [c('time', 0.01, 2, 0.01, 0.37, "s"), c('input', 0, 1, 0.01, 0.8, "gain"), c('return', 0, 1.5, 0.01, 0.25, "gain")],
        {"wet":1}),
    'catalogue.drift-lfo.selected': selected('catalogue.drift-lfo.selected', 'catalogue.drift-lfo', "Grandpa’s Drift LFO", 's1a.lfo',
        [p("out", 'CV', 'out', 1)],
        [c('rate', 0.02, 20, 0.001, 0.06, "Hz"), c('amount', 0, 1, 0.01, 0.35, "bipolar CV peak")],
        {"waveform":"sine","driftEnabled":false}),
    'catalogue.needle-mixer.selected': selected('catalogue.needle-mixer.selected', 'catalogue.needle-mixer', "Needle Mixer", 'audio.mix',
        [p("a", 'AUDIO', 'in', 1), p("b", 'AUDIO', 'in', 1), p("out", 'AUDIO', 'out', 1)],
        [c('aLevel', 0, 2, 0.01, 0.6, "gain"), c('bLevel', 0, 2, 0.01, 0.35, "gain"), c('master', 0, 2, 0.01, 0.8, "gain")],
        {}),
    'catalogue.thunderclock.selected': selected('catalogue.thunderclock.selected', 'catalogue.thunderclock', "Thunderclock Driver", 'clock.master',
        [p("out", 'CLOCK', 'out', 1), p("reset", 'TRIG', 'out', 1)],
        [c('rate', 0.02, 20, 0.001, 3, "Hz"), c('pulseWidth', 0.001, 0.5, 0.001, 0.05, "fraction of clock period")],
        {"run":true,"initialPhase":0}),
    'catalogue.lunar-divider.selected': selected('catalogue.lunar-divider.selected', 'catalogue.lunar-divider', "Lunar Pulse Divider", 'clock.divide',
        [p("in", 'CLOCK', 'in', 1), p("reset", 'TRIG', 'in', 1), p("out", 'CLOCK', 'out', 1)],
        [c('division', 1, 64, 1, 3, "positive integer input-edge count", true), c('phase', 0, 63, 1, 0, "integer tick offset", true)],
        {"firstEdgeOnReset":true}),
    'catalogue.thunderstrike-ad.selected': selected('catalogue.thunderstrike-ad.selected', 'catalogue.thunderstrike-ad', "Thunderstrike ENV", 'function.ad',
        [p("trigger", 'TRIG', 'in', 1, true), p("out", 'CV', 'out', 1)],
        [c('attack', 0.0001, 120, 0.0001, 0.002, "s"), c('decay', 0.0001, 120, 0.0001, 0.18, "s")],
        {"curve":"exponential","retrigger":"restart-from-zero","initialValue":0}),
    'catalogue.solar-wind.selected': selected('catalogue.solar-wind.selected', 'catalogue.solar-wind', "Solar Wind Noise", 'noise.color',
        [p("out", 'AUDIO', 'out', 1)],
        [c('level', 0, 1, 0.01, 0.35, "gain"), c('colorCutoff', 20, 12000, 1, 5000, "Hz")],
        {"colorMode":"lowpass"}),
    'catalogue.vapor-fm.selected': selected('catalogue.vapor-fm.selected', 'catalogue.vapor-fm', "Vaporline FM Source", 'osc.linear-fm',
        [p("pitch", 'CV', 'in', 1), p("linear-fm", 'AUDIO', 'in', 1), p("out", 'AUDIO', 'out', 1)],
        [c('frequency', 40, 1200, 1, 220, "Hz"), c('fmDepth', 0, 4000, 1, 850, "Hz per normalized AUDIO unit")],
        {"waveform":"sine","internalModulatorEnabled":false,"frequencyBoundsHz":[20,12000]}),
    'catalogue.thunderfold.selected': selected('catalogue.thunderfold.selected', 'catalogue.thunderfold', "Thunderfold VCF", 'shape.wavefolder',
        [p("in", 'AUDIO', 'in', 1), p("fold", 'CV', 'in', 1), p("out", 'AUDIO', 'out', 1)],
        [c('fold', 0, 20, 0.01, 6, "dimensionless fold drive"), c('symmetry', -1, 1, 0.01, 0, "normalized input bias")],
        {"foldCvDepth":0.7}),
    'catalogue.solar-quad.audio-audio-cv-cv': selected('catalogue.solar-quad.audio-audio-cv-cv', 'catalogue.solar-quad', "Solar Quad Attenuator", 'signal.attenuvert',
        [p("in1", 'AUDIO', 'in', 1), p("out1", 'AUDIO', 'out', 1), p("in2", 'AUDIO', 'in', 1), p("out2", 'AUDIO', 'out', 1), p("in3", 'CV', 'in', 1), p("out3", 'CV', 'out', 1), p("in4", 'CV', 'in', 1), p("out4", 'CV', 'out', 1)],
        [c('gain1', -2, 2, 0.01, 0.4, "signed gain"), c('gain2', -2, 2, 0.01, 0.22, "signed gain"), c('gain3', -2, 2, 0.01, 0.25, "signed gain"), c('gain4', -2, 2, 0.01, 1, "signed gain")],
        {"laneFamilies":["AUDIO","AUDIO","CV","CV"]}),
    'catalogue.solar-quad.cv4': selected('catalogue.solar-quad.cv4', 'catalogue.solar-quad', "Solar Quad Attenuator", 'signal.attenuvert.cv4',
        [p("in1", 'CV', 'in', 1), p("out1", 'CV', 'out', 1), p("in2", 'CV', 'in', 1), p("out2", 'CV', 'out', 1), p("in3", 'CV', 'in', 1), p("out3", 'CV', 'out', 1), p("in4", 'CV', 'in', 1), p("out4", 'CV', 'out', 1)],
        [c('gain1', -2, 2, 0.01, 0.4, "signed gain"), c('gain2', -2, 2, 0.01, 0.22, "signed gain"), c('gain3', -2, 2, 0.01, 0.25, "signed gain"), c('gain4', -2, 2, 0.01, 1, "signed gain")],
        {"laneFamilies":["CV","CV","CV","CV"]}),
    'catalogue.fossil-modal.selected': selected('catalogue.fossil-modal.selected', 'catalogue.fossil-modal', "Fossil Resonator", 'resonator.modal',
        [p("exciter", 'AUDIO', 'in', 1), p("pitch", 'CV', 'in', 1), p("damping", 'CV', 'in', 1), p("out", 'AUDIO', 'out', 1)],
        [c('frequency', 40, 1200, 1, 137, "Hz reference"), c('damping', 0, 1, 0.01, 0.55, "normalized [0,1]"), c('structure', 0, 1, 0.01, 0.3, "normalized [0,1]"), c('excitationPosition', 0, 1, 0.01, 0.4, "normalized [0,1]")],
        {"dampingCvDepth":0.3,"modeRatios":[1,2.76,5.4]}),
    'catalogue.rustleaf-functions.selected': selected('catalogue.rustleaf-functions.selected', 'catalogue.rustleaf-functions', "Rustleaf Function Duo", 'function.cycle-eoc',
        [p("a.trigger", 'TRIG', 'in', 1, true), p("a.out", 'CV', 'out', 1), p("a.eoc", 'TRIG', 'out', 1), p("b.trigger", 'TRIG', 'in', 1, true), p("b.out", 'CV', 'out', 1), p("b.eoc", 'TRIG', 'out', 1)],
        [c('riseA', 0.0001, 120, 0.0001, 0.004, "s"), c('fallA', 0.0001, 120, 0.0001, 0.85, "s"), c('riseB', 0.0001, 120, 0.0001, 11, "s"), c('fallB', 0.0001, 120, 0.0001, 17, "s")],
        {"cycleA":true,"cycleB":true,"curveA":"exponential","curveB":"linear","initialValueA":0,"initialValueB":0}),
    'catalogue.quantum-hold.selected': selected('catalogue.quantum-hold.selected', 'catalogue.quantum-hold', "Quantum Sprinkle", 'memory.sample-hold',
        [p("value", 'CV', 'in', 1), p("sample", 'TRIG', 'in', 1, true), p("out", 'CV', 'out', 1)],
        [c('initialValue', -8, 8, 0.01, 0, "generic CV")],
        {}),
};
